### ISSUE TITLE
Ignore IDE files and .pyc and *.db

### ISSUE THREAD

**Issue by osule** [andela-joyebanji/AndelaRoomAllocator#1]
You may want to ignore files from your editor, python bytecode files like *pyc & *pyo, and *.db files. 

Here is a [gitignore template](https://github.com/github/gitignore/blob/master/Python.gitignore) that should work for most Python projects.

**Comment by andela-joyebanji** [comment]
Fixed https://github.com/andela-joyebanji/AndelaRoomAllocator/commit/064ad694a1563b3b8228ec1cc6515462f57d0e5f
