### ISSUE TITLE
Is there a way we can make this better?

### ISSUE THREAD

**Issue by osule** [andela-joyebanji/AndelaRoomAllocator#2]
We can refactor [this](https://github.com/andela-joyebanji/AndelaRoomAllocator/blob/develop/app/allocator.py#L86-L94) nested conditional using guard clauses.
We can maybe have something like [here](http://pastebin.com/28QKsjBP):

**Comment by andela-joyebanji** [comment]
Fixed https://github.com/andela-joyebanji/AndelaRoomAllocator/commit/064ad694a1563b3b8228ec1cc6515462f57d0e5f
