### ISSUE TITLE
Extra blank

### ISSUE THREAD

**Issue by osule** [andela-joyebanji/AndelaRoomAllocator#3]
There is an extra blank [here](https://github.com/andela-joyebanji/AndelaRoomAllocator/blob/develop/app/allocator.py#L111) that we may have introduced in-deliberately.

**Comment by andela-joyebanji** [comment]
Fixed https://github.com/andela-joyebanji/AndelaRoomAllocator/commit/064ad694a1563b3b8228ec1cc6515462f57d0e5f
