### ISSUE TITLE
Explicit path

### ISSUE THREAD

**Issue by osule** [andela-joyebanji/AndelaRoomAllocator#4]
This [path](https://github.com/andela-joyebanji/AndelaRoomAllocator/blob/develop/app/amity.py#L4) been inserted into the available paths for sys lookup is very explicit. If tests fail when this line is removed, we might want to look at using a [virtual environment](https://virtualenv.pypa.io/en/stable/) for your dependencies.

**Comment by andela-joyebanji** [comment]
Nice.. I've been looking for that line of code. (funny enough). Thanks

**Comment by andela-joyebanji** [comment]
Fixed https://github.com/andela-joyebanji/AndelaRoomAllocator/commit/064ad694a1563b3b8228ec1cc6515462f57d0e5f
